
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the MarketSynthDomainServiceData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.MarketSynthDomainServiceData MarketSynthDomainServiceData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.MarketSynthDomainServiceData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.MarketSynthDomainServiceData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.MarketSynthDomainServiceData> MarketSynthDomainServiceData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.MarketSynthDomainServiceData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.MarketSynthDomainServiceData>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.MarketSynthDomainServiceData>.Entry
                    MarketSynthDomainServiceData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.MarketSynthDomainServiceData>.Entry(
                        "MarketSynthDomainServiceData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._MarketSynthDomainServiceData_Stub);
                private static void _MarketSynthDomainServiceData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.MarketSynthDomainServiceData>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._MarketSynthDomainServiceData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.MarketSynthDomainServiceData>.Data _MarketSynthDomainServiceData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the MarketSynthDomainServiceData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class MarketSynthDomainServiceData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass>
    {
        #region Constructors
    
        public MarketSynthDomainServiceData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the MarketDatas entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.MarketData> MarketDatas
        {
            get
            {
                return global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.GetValue(this, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.MarketDatas);
            }
        }
        
        /// <summary>
        /// Gets the Indicators entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Indicator> Indicators
        {
            get
            {
                return global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.GetValue(this, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.Indicators);
            }
        }
        
        /// <summary>
        /// Gets the Studies entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Study> Studies
        {
            get
            {
                return global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.GetValue(this, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.Studies);
            }
        }
        
        /// <summary>
        /// Gets the StudyIndicators entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.StudyIndicator> StudyIndicators
        {
            get
            {
                return global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.GetValue(this, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.StudyIndicators);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        /// <param name="symbol">
        /// No Modeled Description Available
        /// </param>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.MarketData> GetMarketDataBySymbol(string symbol)
        {
            return this.Details.Methods.GetMarketDataBySymbol.CreateInvocation(symbol).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.MarketData MarketDatas_Single(global::System.Nullable<global::System.Guid> Id)
        {
            return this.Details.Methods.MarketDatas_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.MarketData MarketDatas_SingleOrDefault(global::System.Nullable<global::System.Guid> Id)
        {
            return this.Details.Methods.MarketDatas_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Indicator Indicators_Single(global::System.Nullable<global::System.Guid> Id)
        {
            return this.Details.Methods.Indicators_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Indicator Indicators_SingleOrDefault(global::System.Nullable<global::System.Guid> Id)
        {
            return this.Details.Methods.Indicators_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Study Studies_Single(global::System.Nullable<global::System.Guid> Id)
        {
            return this.Details.Methods.Studies_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Study Studies_SingleOrDefault(global::System.Nullable<global::System.Guid> Id)
        {
            return this.Details.Methods.Studies_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.StudyIndicator StudyIndicators_Single(global::System.Nullable<global::System.Guid> Id)
        {
            return this.Details.Methods.StudyIndicators_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.StudyIndicator StudyIndicators_SingleOrDefault(global::System.Nullable<global::System.Guid> Id)
        {
            return this.Details.Methods.StudyIndicators_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        /// <param name="instrument">
        /// No Modeled Description Available
        /// </param>
        /// <param name="indicator">
        /// No Modeled Description Available
        /// </param>
        public global::LightSwitchApplication.StudyIndicator GetStudyIndicator(string instrument, string indicator)
        {
            return this.Details.Methods.GetStudyIndicator.CreateInvocation(instrument, indicator).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySet, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.GetMarketDataBySymbol;
                var initializePropertyEntry = global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.MarketDatas;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData> GetMarketDataBySymbol
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.GetMarketDataBySymbol) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData> MarketDatas_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.MarketDatas_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData> MarketDatas_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.MarketDatas_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator> Indicators_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.Indicators_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator> Indicators_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.Indicators_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study> Studies_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.Studies_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study> Studies_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.Studies_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator> StudyIndicators_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.StudyIndicators_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator> StudyIndicators_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.StudyIndicators_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator> GetStudyIndicator
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties.GetStudyIndicator) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData> MarketDatas
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.MarketDatas) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator> Indicators
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.Indicators) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study> Studies
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.Studies) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator> StudyIndicators
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties.StudyIndicators) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Entry
                    GetMarketDataBySymbol = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Entry(
                        "GetMarketDataBySymbol",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._GetMarketDataBySymbol_Stub);
                private static void _GetMarketDataBySymbol_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._GetMarketDataBySymbol, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Entry
                    MarketDatas_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Entry(
                        "MarketDatas_Single",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._MarketDatas_Single_Stub);
                private static void _MarketDatas_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._MarketDatas_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Entry
                    MarketDatas_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Entry(
                        "MarketDatas_SingleOrDefault",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._MarketDatas_SingleOrDefault_Stub);
                private static void _MarketDatas_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._MarketDatas_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Entry
                    Indicators_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Entry(
                        "Indicators_Single",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._Indicators_Single_Stub);
                private static void _Indicators_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._Indicators_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Entry
                    Indicators_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Entry(
                        "Indicators_SingleOrDefault",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._Indicators_SingleOrDefault_Stub);
                private static void _Indicators_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._Indicators_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Entry
                    Studies_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Entry(
                        "Studies_Single",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._Studies_Single_Stub);
                private static void _Studies_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._Studies_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Entry
                    Studies_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Entry(
                        "Studies_SingleOrDefault",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._Studies_SingleOrDefault_Stub);
                private static void _Studies_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._Studies_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Entry
                    StudyIndicators_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Entry(
                        "StudyIndicators_Single",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._StudyIndicators_Single_Stub);
                private static void _StudyIndicators_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._StudyIndicators_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Entry
                    StudyIndicators_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Entry(
                        "StudyIndicators_SingleOrDefault",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._StudyIndicators_SingleOrDefault_Stub);
                private static void _StudyIndicators_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._StudyIndicators_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Entry
                    GetStudyIndicator = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Entry(
                        "GetStudyIndicator",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.MethodSetProperties._GetStudyIndicator_Stub);
                private static void _GetStudyIndicator_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._GetStudyIndicator, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Entry
                    MarketDatas = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Entry(
                        "MarketDatas",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties._MarketDatas_Stub);
                private static void _MarketDatas_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._MarketDatas, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Entry
                    Indicators = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Entry(
                        "Indicators",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties._Indicators_Stub);
                private static void _Indicators_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._Indicators, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Entry
                    Studies = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Entry(
                        "Studies",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties._Studies_Stub);
                private static void _Studies_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._Studies, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Entry
                    StudyIndicators = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Entry(
                        "StudyIndicators",
                        global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass.PropertySetProperties._StudyIndicators_Stub);
                private static void _StudyIndicators_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Data> c, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass d, object sf)
                {
                    c(d, ref d._StudyIndicators, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Data _MarketDatas;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Data _Indicators;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Data _Studies;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Data _StudyIndicators;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Data _GetMarketDataBySymbol;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Data _MarketDatas_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.MarketData>.Data _MarketDatas_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Data _Indicators_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Indicator>.Data _Indicators_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Data _Studies_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.Study>.Data _Studies_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Data _StudyIndicators_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Data _StudyIndicators_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.MarketSynthDomainServiceData, global::LightSwitchApplication.MarketSynthDomainServiceData.DetailsClass, global::LightSwitchApplication.StudyIndicator>.Data _GetStudyIndicator;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
