

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Study : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Study entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Study()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Study(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Study> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Study.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Study_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Study_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return global::LightSwitchApplication.Study.DetailsClass.GetValue(this, global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Study.DetailsClass.SetValue(this, global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string InstrumentName
        {
            get
            {
                return global::LightSwitchApplication.Study.DetailsClass.GetValue(this, global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.InstrumentName);
            }
            set
            {
                global::LightSwitchApplication.Study.DetailsClass.SetValue(this, global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.InstrumentName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InstrumentName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InstrumentName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InstrumentName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid IndicatorId
        {
            get
            {
                return global::LightSwitchApplication.Study.DetailsClass.GetValue(this, global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.IndicatorId);
            }
            set
            {
                global::LightSwitchApplication.Study.DetailsClass.SetValue(this, global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.IndicatorId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IndicatorId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IndicatorId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IndicatorId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string IndicatorName
        {
            get
            {
                return global::LightSwitchApplication.Study.DetailsClass.GetValue(this, global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.IndicatorName);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IndicatorName_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IndicatorName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Study,
                global::LightSwitchApplication.Study.DetailsClass,
                global::LightSwitchApplication.Study.DetailsClass.IImplementation,
                global::LightSwitchApplication.Study.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass>.Entry
                __StudyEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass>.Entry(
                    global::LightSwitchApplication.Study.DetailsClass.__Study_CreateNew,
                    global::LightSwitchApplication.Study.DetailsClass.__Study_Created,
                    global::LightSwitchApplication.Study.DetailsClass.__Study_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Study __Study_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Study> es)
            {
                return new global::LightSwitchApplication.Study(es);
            }
            private static void __Study_Created(global::LightSwitchApplication.Study e)
            {
                e.Study_Created();
            }
            private static bool __Study_AllowSaveWithErrors(global::LightSwitchApplication.Study e)
            {
                bool result = false;
                e.Study_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Study.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string> InstrumentName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.InstrumentName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid> IndicatorId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.IndicatorId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string> IndicatorName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties.IndicatorName) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid Id { get; set; }
                new string InstrumentName { get; set; }
                new global::System.Guid IndicatorId { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>.Entry(
                        "Id",
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Study.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.Study.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Study e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Study e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static global::System.Guid _Id_GetImplementationValue(global::LightSwitchApplication.Study.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Study.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Study e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>.Entry
                    InstrumentName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>.Entry(
                        "InstrumentName",
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._InstrumentName_Stub,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._InstrumentName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._InstrumentName_Validate,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._InstrumentName_GetImplementationValue,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._InstrumentName_SetImplementationValue,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._InstrumentName_OnValueChanged);
                private static void _InstrumentName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Study.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>.Data> c, global::LightSwitchApplication.Study.DetailsClass d, object sf)
                {
                    c(d, ref d._InstrumentName, sf);
                }
                private static bool _InstrumentName_ComputeIsReadOnly(global::LightSwitchApplication.Study e)
                {
                    bool result = false;
                    e.InstrumentName_IsReadOnly(ref result);
                    return result;
                }
                private static void _InstrumentName_Validate(global::LightSwitchApplication.Study e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.InstrumentName_Validate(r);
                }
                private static string _InstrumentName_GetImplementationValue(global::LightSwitchApplication.Study.DetailsClass d)
                {
                    return d.ImplementationEntity.InstrumentName;
                }
                private static void _InstrumentName_SetImplementationValue(global::LightSwitchApplication.Study.DetailsClass d, string v)
                {
                    d.ImplementationEntity.InstrumentName = v;
                }
                private static void _InstrumentName_OnValueChanged(global::LightSwitchApplication.Study e)
                {
                    e.InstrumentName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>.Entry
                    IndicatorId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>.Entry(
                        "IndicatorId",
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorId_Stub,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorId_ComputeIsReadOnly,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorId_Validate,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorId_GetImplementationValue,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorId_SetImplementationValue,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorId_OnValueChanged);
                private static void _IndicatorId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Study.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.Study.DetailsClass d, object sf)
                {
                    c(d, ref d._IndicatorId, sf);
                }
                private static bool _IndicatorId_ComputeIsReadOnly(global::LightSwitchApplication.Study e)
                {
                    bool result = false;
                    e.IndicatorId_IsReadOnly(ref result);
                    return result;
                }
                private static void _IndicatorId_Validate(global::LightSwitchApplication.Study e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IndicatorId_Validate(r);
                }
                private static global::System.Guid _IndicatorId_GetImplementationValue(global::LightSwitchApplication.Study.DetailsClass d)
                {
                    return d.ImplementationEntity.IndicatorId;
                }
                private static void _IndicatorId_SetImplementationValue(global::LightSwitchApplication.Study.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.IndicatorId = v;
                }
                private static void _IndicatorId_OnValueChanged(global::LightSwitchApplication.Study e)
                {
                    e.IndicatorId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>.Entry
                    IndicatorName = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>.Entry(
                        "IndicatorName",
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorName_Stub,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorName_Validate,
                        global::LightSwitchApplication.Study.DetailsClass.PropertySetProperties._IndicatorName_ComputeValue);
                private static void _IndicatorName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Study.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>.Data> c, global::LightSwitchApplication.Study.DetailsClass d, object sf)
                {
                    c(d, ref d._IndicatorName, sf);
                }
                private static void _IndicatorName_Validate(global::LightSwitchApplication.Study e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IndicatorName_Validate(r);
                }
                private static string _IndicatorName_ComputeValue(global::LightSwitchApplication.Study e)
                {
                    string value = default(string);
                    e.IndicatorName_Compute(ref value);
                    return value;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>.Data _InstrumentName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, global::System.Guid>.Data _IndicatorId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Study, global::LightSwitchApplication.Study.DetailsClass, string>.Data _IndicatorName;
            
        }
    
        #endregion
    }
    
    #endregion
}
