

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class StudyIndicator : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the StudyIndicator entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public StudyIndicator()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public StudyIndicator(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.StudyIndicator> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.StudyIndicator.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyIndicator_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyIndicator_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return global::LightSwitchApplication.StudyIndicator.DetailsClass.GetValue(this, global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.StudyIndicator.DetailsClass.SetValue(this, global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Label
        {
            get
            {
                return global::LightSwitchApplication.StudyIndicator.DetailsClass.GetValue(this, global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.Label);
            }
            set
            {
                global::LightSwitchApplication.StudyIndicator.DetailsClass.SetValue(this, global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.Label, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Label_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Label_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Label_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PointData
        {
            get
            {
                return global::LightSwitchApplication.StudyIndicator.DetailsClass.GetValue(this, global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.PointData);
            }
            set
            {
                global::LightSwitchApplication.StudyIndicator.DetailsClass.SetValue(this, global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.PointData, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PointData_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PointData_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PointData_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.StudyIndicator,
                global::LightSwitchApplication.StudyIndicator.DetailsClass,
                global::LightSwitchApplication.StudyIndicator.DetailsClass.IImplementation,
                global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass>.Entry
                __StudyIndicatorEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass>.Entry(
                    global::LightSwitchApplication.StudyIndicator.DetailsClass.__StudyIndicator_CreateNew,
                    global::LightSwitchApplication.StudyIndicator.DetailsClass.__StudyIndicator_Created,
                    global::LightSwitchApplication.StudyIndicator.DetailsClass.__StudyIndicator_AllowSaveWithErrors);
            private static global::LightSwitchApplication.StudyIndicator __StudyIndicator_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.StudyIndicator> es)
            {
                return new global::LightSwitchApplication.StudyIndicator(es);
            }
            private static void __StudyIndicator_Created(global::LightSwitchApplication.StudyIndicator e)
            {
                e.StudyIndicator_Created();
            }
            private static bool __StudyIndicator_AllowSaveWithErrors(global::LightSwitchApplication.StudyIndicator e)
            {
                bool result = false;
                e.StudyIndicator_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, global::System.Guid> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, global::System.Guid>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string> Label
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.Label) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string> PointData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties.PointData) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new global::System.Guid Id { get; set; }
                new string Label { get; set; }
                new string PointData { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, global::System.Guid>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, global::System.Guid>.Entry(
                        "Id",
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.StudyIndicator.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, global::System.Guid>.Data> c, global::LightSwitchApplication.StudyIndicator.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.StudyIndicator e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.StudyIndicator e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static global::System.Guid _Id_GetImplementationValue(global::LightSwitchApplication.StudyIndicator.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.StudyIndicator.DetailsClass d, global::System.Guid v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.StudyIndicator e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>.Entry
                    Label = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>.Entry(
                        "Label",
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Label_Stub,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Label_ComputeIsReadOnly,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Label_Validate,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Label_GetImplementationValue,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Label_SetImplementationValue,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._Label_OnValueChanged);
                private static void _Label_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.StudyIndicator.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>.Data> c, global::LightSwitchApplication.StudyIndicator.DetailsClass d, object sf)
                {
                    c(d, ref d._Label, sf);
                }
                private static bool _Label_ComputeIsReadOnly(global::LightSwitchApplication.StudyIndicator e)
                {
                    bool result = false;
                    e.Label_IsReadOnly(ref result);
                    return result;
                }
                private static void _Label_Validate(global::LightSwitchApplication.StudyIndicator e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Label_Validate(r);
                }
                private static string _Label_GetImplementationValue(global::LightSwitchApplication.StudyIndicator.DetailsClass d)
                {
                    return d.ImplementationEntity.Label;
                }
                private static void _Label_SetImplementationValue(global::LightSwitchApplication.StudyIndicator.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Label = v;
                }
                private static void _Label_OnValueChanged(global::LightSwitchApplication.StudyIndicator e)
                {
                    e.Label_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>.Entry
                    PointData = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>.Entry(
                        "PointData",
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._PointData_Stub,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._PointData_ComputeIsReadOnly,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._PointData_Validate,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._PointData_GetImplementationValue,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._PointData_SetImplementationValue,
                        global::LightSwitchApplication.StudyIndicator.DetailsClass.PropertySetProperties._PointData_OnValueChanged);
                private static void _PointData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.StudyIndicator.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>.Data> c, global::LightSwitchApplication.StudyIndicator.DetailsClass d, object sf)
                {
                    c(d, ref d._PointData, sf);
                }
                private static bool _PointData_ComputeIsReadOnly(global::LightSwitchApplication.StudyIndicator e)
                {
                    bool result = false;
                    e.PointData_IsReadOnly(ref result);
                    return result;
                }
                private static void _PointData_Validate(global::LightSwitchApplication.StudyIndicator e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PointData_Validate(r);
                }
                private static string _PointData_GetImplementationValue(global::LightSwitchApplication.StudyIndicator.DetailsClass d)
                {
                    return d.ImplementationEntity.PointData;
                }
                private static void _PointData_SetImplementationValue(global::LightSwitchApplication.StudyIndicator.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PointData = v;
                }
                private static void _PointData_OnValueChanged(global::LightSwitchApplication.StudyIndicator e)
                {
                    e.PointData_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, global::System.Guid>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>.Data _Label;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.StudyIndicator, global::LightSwitchApplication.StudyIndicator.DetailsClass, string>.Data _PointData;
            
        }
    
        #endregion
    }
    
    #endregion
}
